### ISSUE TITLE
Can't start created App in debug

### ISSUE THREAD

**Issue by paul70078** [Skycoder42/QtMvvm#1]
I've created an App and added an empty View+Viewmodel (according to usage-guide). When I try to start the app in debug i get following Output:
```
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/App.qml:2 plugin cannot be loaded for module "de.skycoder42.QtMvvm.Quick": Die Bibliothek C:\Qt\5.11.1\msvc2017_64\qml\de\skycoder42\QtMvvm\Quick\declarative_mvvmquickd.dll kann nicht geladen werden: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
```

Starting in Release works

**Comment by Skycoder42** [comment]
Thats kind of surprising as there are no custom DLL initialization routines in that plugin. I will try and see if I can reproduce that error

**Comment by paul70078** [comment]
I have Qt Version 5.11.1 msvc2017_64 with the QtMvvm Plugin installed using you plugin source with the Qt Maintenance Tool

**Comment by Skycoder42** [comment]
Ok. So I manage to reproduce the issue. The reason seems to be that the `Qt5MvvmQuick.dll` is only loaded by the qml plugin and not by the application itself which leads to the error. Allthough I have no Idea why exactly thats the case. Could be a bug in Qt...

Now as a workaround, all you need to do is to reference any class from the QtMvvmQuick module in your cpp code to ensure that windows actually loads the `Qt5MvvmQuick.dll` when your application is started. This way the DLL is loaded before the QML plugin and the error does not appear.

Please try adding the following to your `main.cpp`:
```.cpp
QtMvvm::QuickPresenter::getInputViewFactory(); //does nothing, except referencing the DLL
QQmlApplicationEngine engine;
// ...
```

**Comment by Skycoder42** [comment]
This really seems to be a bug in QT. See [QTBUG-69963](https://bugreports.qt.io/browse/QTBUG-69963).
